-- توسيع الأدوات من 12 إلى 50+
-- شغّل هذا في Supabase SQL Editor

INSERT INTO tools (slug, name, name_ar, tagline_ar, description_ar, category, pricing, price_monthly, price_yearly, features, pros, cons, website_url, logo_url, rating, reviews_count, tags, is_featured, launched_at) VALUES

-- ── CHATBOTS ──────────────────────────────────────────────────────────────
('grok', 'Grok', 'غروك', 'الذكاء الاصطناعي من إكس (تويتر)', 'غروك هو نموذج الذكاء الاصطناعي من شركة xAI المملوكة لإيلون ماسك. يتميز بالوصول الفوري لمنشورات X وأسلوب إجابة جريء وغير رسمي. متاح لمشتركي X Premium.', 'chatbot', 'freemium', 8, null, ARRAY['وصول فوري لمنشورات X', 'أسلوب محادثة غير رسمي', 'تحليل الصور', 'توليد الكود', 'بحث في الوقت الحقيقي'], ARRAY['بيانات حديثة من X', 'مجاني جزئياً', 'ردود جريئة وصريحة'], ARRAY['يتطلب اشتراك X Premium للنسخة الكاملة', 'محدود خارج X'], 'https://x.ai/grok', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Grok_logo.svg/120px-Grok_logo.svg.png', 4.2, 1840, ARRAY['chatbot', 'ai', 'x', 'twitter', 'elon-musk'], false, '2023-11-04'),

('meta-ai', 'Meta AI', 'ميتا AI', 'مساعد الذكاء الاصطناعي من فيسبوك وواتساب وإنستغرام', 'ميتا AI هو المساعد الذكي من شركة Meta المدمج في واتساب وإنستغرام وفيسبوك وماسنجر. مبني على نموذج Llama 3 ويستطيع توليد الصور والإجابة على الأسئلة داخل التطبيقات مباشرة.', 'chatbot', 'free', null, null, ARRAY['مدمج في واتساب وإنستغرام', 'توليد الصور مجاناً', 'مبني على Llama 3', 'متعدد اللغات', 'بحث ويب'], ARRAY['مجاني كلياً', 'لا يحتاج تطبيق منفصل', 'يعمل داخل واتساب'], ARRAY['خصوصية البيانات مع Meta', 'أقل دقة من GPT-4'], 'https://ai.meta.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/120px-Meta_Platforms_Inc._logo.svg.png', 4.0, 3200, ARRAY['chatbot', 'meta', 'whatsapp', 'instagram', 'free'], false, '2023-09-27'),

('microsoft-copilot', 'Microsoft Copilot', 'مايكروسوفت كوبايلوت', 'الذكاء الاصطناعي المدمج في ويندوز وأوفيس', 'مايكروسوفت كوبايلوت هو مساعد الذكاء الاصطناعي المدمج في ويندوز 11 وأوفيس 365 ومتصفح Edge. مبني على GPT-4 ويساعد في كتابة المستندات وتحليل البيانات وتلخيص الاجتماعات.', 'chatbot', 'freemium', 20, null, ARRAY['مدمج في Office 365', 'تلخيص الاجتماعات', 'إنشاء وثائق Word', 'تحليل بيانات Excel', 'توليد صور DALL-E'], ARRAY['مدمج في أدوات مايكروسوفت', 'مجاني في المتصفح', 'واجهة عربية'], ARRAY['الإصدار الكامل مدفوع', 'يتطلب حساب Microsoft'], 'https://copilot.microsoft.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Microsoft_365_Copilot_Icon.svg/120px-Microsoft_365_Copilot_Icon.svg.png', 4.3, 5600, ARRAY['chatbot', 'microsoft', 'office', 'productivity', 'windows'], true, '2023-03-16'),

('llama', 'Llama (Meta)', 'لاما (ميتا)', 'نموذج الذكاء الاصطناعي مفتوح المصدر من ميتا', 'لاما هو نموذج لغوي مفتوح المصدر من Meta يمكن تثبيته محلياً على حاسوبك. متاح للباحثين والمطورين مجاناً ويستخدم كأساس لكثير من نماذج الذكاء الاصطناعي الأخرى.', 'chatbot', 'free', null, null, ARRAY['مفتوح المصدر', 'يعمل محلياً', 'بدون رسوم', 'قابل للتخصيص', 'نماذج بأحجام متعددة'], ARRAY['مجاني تماماً', 'خصوصية كاملة', 'يعمل بدون إنترنت'], ARRAY['يتطلب مهارات تقنية', 'يحتاج أجهزة قوية'], 'https://llama.meta.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Meta-Logo.png/120px-Meta-Logo.png', 4.1, 980, ARRAY['open-source', 'llm', 'local', 'developer', 'free'], false, '2023-02-24'),

('mistral', 'Mistral AI', 'ميسترال AI', 'نماذج ذكاء اصطناعي أوروبية مفتوحة المصدر', 'ميسترال هي شركة فرنسية تطور نماذج ذكاء اصطناعي مفتوحة المصدر عالية الكفاءة. نماذجها تنافس GPT-4 بموارد أقل بكثير وتستخدم على نطاق واسع في المشاريع التقنية.', 'chatbot', 'freemium', 14, null, ARRAY['نماذج مفتوحة المصدر', 'كفاءة عالية', 'API متاح', 'نموذج Mixtral', 'خادم Le Chat مجاني'], ARRAY['كفاءة عالية وتكلفة منخفضة', 'مفتوح المصدر', 'أوروبي التصنيع'], ARRAY['أقل شهرة من GPT', 'قاعدة مستخدمين أصغر'], 'https://mistral.ai', 'https://mistral.ai/images/logo_hubc88c4ece131b91c7cb753f40e9e1cc5_2589_256x0_resize_q97_h2_lanczos_3.webp', 4.2, 720, ARRAY['open-source', 'french', 'llm', 'api', 'developer'], false, '2023-09-27'),

('cohere', 'Cohere', 'كوهير', 'ذكاء اصطناعي مخصص للأعمال والمؤسسات', 'كوهير منصة ذكاء اصطناعي موجهة للمؤسسات توفر نماذج Command وEmbed لمعالجة النصوص والبحث الدلالي. تستخدمها شركات كبرى لبناء تطبيقات داخلية آمنة.', 'chatbot', 'freemium', 0, null, ARRAY['نموذج Command للمحادثة', 'Embed للبحث الدلالي', 'نشر في السحابة الخاصة', 'API قوي', 'أمان مؤسسي'], ARRAY['موجه للأعمال', 'أمان عالٍ', 'API مجاني للتجربة'], ARRAY['ليس للمستخدمين الأفراد', 'واجهة تقنية'], 'https://cohere.com', 'https://asset.brandfetch.io/idoXB5IJDI/idZCx0GYJR.jpeg', 3.9, 340, ARRAY['enterprise', 'api', 'nlp', 'search', 'business'], false, '2021-11-01'),

-- ── IMAGE ──────────────────────────────────────────────────────────────────
('adobe-firefly', 'Adobe Firefly', 'أدوبي فايرفلاي', 'توليد الصور بالذكاء الاصطناعي من أدوبي', 'أدوبي فايرفلاي هو محرك الذكاء الاصطناعي لتوليد الصور من Adobe مدمج في Photoshop وIllustrator. مدرّب على صور مرخّصة تجارياً مما يجعله آمناً للاستخدام التجاري.', 'image', 'freemium', 5, null, ARRAY['مدمج في Photoshop', 'آمن تجارياً', 'Generative Fill', 'توليد نصوص في الصور', 'تغيير الخلفيات'], ARRAY['آمن للاستخدام التجاري', 'مدمج في Adobe', 'جودة احترافية'], ARRAY['يتطلب اشتراك Adobe', 'أبطأ من المنافسين'], 'https://firefly.adobe.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Adobe_Firefly_wordmark.svg/120px-Adobe_Firefly_wordmark.svg.png', 4.5, 4200, ARRAY['image', 'adobe', 'photoshop', 'commercial', 'design'], true, '2023-03-21'),

('canva-ai', 'Canva AI', 'كانفا AI', 'تصميم بالذكاء الاصطناعي للجميع', 'كانفا AI مجموعة أدوات ذكاء اصطناعي داخل منصة كانفا تشمل Magic Write للكتابة وMagic Design للتصاميم وMagic Media لتوليد الصور والفيديو. مثالي للمبتدئين.', 'image', 'freemium', 15, null, ARRAY['Magic Write', 'Magic Design', 'Magic Media', 'إزالة الخلفية', 'تغيير حجم التصاميم'], ARRAY['سهل الاستخدام', 'مدمج مع كانفا', 'قوالب جاهزة'], ARRAY['محدود في النسخة المجانية', 'ليس متخصصاً كـ Midjourney'], 'https://canva.com', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Canva_Logo.png', 4.4, 8900, ARRAY['design', 'canva', 'templates', 'easy', 'beginner'], true, '2023-03-23'),

('ideogram', 'Ideogram', 'آيديوغرام', 'توليد صور مع نصوص واضحة بالذكاء الاصطناعي', 'آيديوغرام متخصص في توليد صور تحتوي نصوص مقروءة بشكل صحيح — وهي مشكلة يعاني منها معظم نماذج الذكاء الاصطناعي. مثالي لتصاميم الشعارات والبطاقات.', 'image', 'freemium', 8, null, ARRAY['نصوص واضحة في الصور', 'شعارات وبطاقات', 'أنماط فنية متعددة', 'مجاني للبدء', 'جودة عالية'], ARRAY['أفضل في النصوص داخل الصور', 'مجاني للاستخدام الأساسي'], ARRAY['أقل مرونة في الأساليب الفنية', 'أبطأ من DALL-E'], 'https://ideogram.ai', 'https://ideogram.ai/assets/ideogram-logo-web.svg', 4.3, 1560, ARRAY['image', 'text-in-image', 'logo', 'typography', 'design'], false, '2023-08-22'),

('leonardo-ai', 'Leonardo AI', 'ليوناردو AI', 'توليد صور احترافية للألعاب والفن الرقمي', 'ليوناردو AI منصة متخصصة في توليد صور الألعاب والفن الرقمي والشخصيات. تتيح ضبطاً دقيقاً للنماذج وتدريب نماذج مخصصة. مفضلة لدى مصممي الألعاب.', 'image', 'freemium', 12, null, ARRAY['نماذج مخصصة للألعاب', 'تدريب النماذج', 'Canvas للتعديل', 'Motion للحركة', '150 صورة مجانية يومياً'], ARRAY['متخصص في فن الألعاب', 'نماذج متعددة', 'مجاني بسخاء'], ARRAY['واجهة معقدة للمبتدئين', 'يتطلب تعلم المصطلحات'], 'https://leonardo.ai', 'https://cdn.prod.website-files.com/64f6f2c0e3f4c5a91c1e823a/64f6f2c0e3f4c5a91c1e8266_logo.svg', 4.4, 2870, ARRAY['image', 'gaming', 'art', 'characters', 'concept-art'], false, '2022-11-01'),

('flux-ai', 'Flux AI', 'فلاكس AI', 'نموذج توليد الصور مفتوح المصدر الأسرع والأكثر دقة', 'فلاكس من Black Forest Labs نموذج توليد صور مفتوح المصدر يتفوق على Stable Diffusion في الدقة والسرعة. يتوفر عبر Replicate وfal.ai وغيرها.', 'image', 'freemium', 0, null, ARRAY['مفتوح المصدر', 'دقة عالية', 'سرعة توليد', 'نماذج schnell وdev وpro', 'متاح عبر API'], ARRAY['مفتوح المصدر', 'دقة استثنائية', 'يتفوق على SDXL'], ARRAY['يتطلب استخدام منصات ثالثة', 'لا واجهة رسمية'], 'https://blackforestlabs.ai', 'https://pbs.twimg.com/profile_images/1820199559581020160/d_UBRGxJ_400x400.jpg', 4.5, 890, ARRAY['image', 'open-source', 'flux', 'api', 'developer'], false, '2024-08-01'),

-- ── VIDEO ──────────────────────────────────────────────────────────────────
('sora', 'Sora', 'سورا', 'توليد فيديو واقعي بالذكاء الاصطناعي من OpenAI', 'سورا نموذج توليد الفيديو من OpenAI القادر على إنشاء فيديوهات عالية الجودة من نص. متاح لمشتركي ChatGPT Plus وPro بحدود شهرية.', 'video', 'paid', 20, null, ARRAY['فيديو حتى 20 ثانية', 'دقة 1080p', 'فيديو من صور', 'تعديل الفيديو', 'أنماط متعددة'], ARRAY['جودة بصرية استثنائية', 'من OpenAI', 'سهولة الاستخدام'], ARRAY['حد شهري محدود', 'مدفوع فقط', 'لا يتوفر في كل الدول'], 'https://sora.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/120px-OpenAI_Logo.svg.png', 4.6, 3400, ARRAY['video', 'openai', 'text-to-video', 'realistic', 'creative'], true, '2024-02-15'),

('kling-ai', 'Kling AI', 'كلينغ AI', 'توليد فيديو صيني متميز بجودة استثنائية', 'كلينغ من شركة Kuaishou الصينية نموذج لتوليد الفيديو يقدم نتائج واقعية مذهلة بأسعار منافسة. يدعم توليد فيديو من نص وصور.', 'video', 'freemium', 10, null, ARRAY['فيديو حتى 3 دقائق', 'حركة واقعية', 'صورة إلى فيديو', 'نص إلى فيديو', 'خطة مجانية'], ARRAY['جودة واقعية عالية', 'سعر منافس', 'خطة مجانية'], ARRAY['خوادم في الصين', 'أوقات انتظار أحياناً'], 'https://klingai.com', 'https://static.klingai.com/images/kling-logo.svg', 4.4, 1230, ARRAY['video', 'chinese', 'realistic', 'affordable', 'image-to-video'], false, '2024-02-06'),

('pika-labs', 'Pika Labs', 'بيكا لابز', 'تحويل الصور والنصوص إلى فيديوهات إبداعية', 'بيكا لابز منصة سهلة الاستخدام لتحويل الصور والنصوص إلى فيديوهات قصيرة. تتميز بإضافة حركة لأي صورة وتعديل الفيديوهات الموجودة.', 'video', 'freemium', 8, null, ARRAY['صورة إلى فيديو', 'نص إلى فيديو', 'تعديل الفيديو', 'إضافة الحركة', 'خطة مجانية'], ARRAY['سهل الاستخدام', 'نتائج سريعة', 'مجاني للبدء'], ARRAY['فيديوهات قصيرة فقط', 'جودة أقل من Sora'], 'https://pika.art', 'https://pika.art/logo.png', 4.1, 2100, ARRAY['video', 'image-to-video', 'creative', 'easy', 'short'], false, '2023-04-01'),

('hailuo-ai', 'Hailuo AI', 'هايلو AI', 'أداة توليد فيديو مجانية بجودة عالية', 'هايلو AI من MiniMax الصينية تقدم توليد فيديو مجاناً بجودة لافتة. اشتهرت بالصوت الواقعي المرافق للفيديو وقدرتها على تصوير المشاعر البشرية.', 'video', 'free', null, null, ARRAY['مجاني تماماً', 'صوت في الفيديو', 'تعبيرات بشرية واقعية', 'جودة عالية', 'سريع'], ARRAY['مجاني كلياً', 'صوت مدمج في الفيديو', 'جودة ممتازة'], ARRAY['حدود يومية', 'خوادم صينية'], 'https://hailuoai.video', 'https://hailuoai.video/logo.png', 4.3, 1780, ARRAY['video', 'free', 'chinese', 'audio', 'realistic'], false, '2024-07-01'),

-- ── AUDIO ──────────────────────────────────────────────────────────────────
('suno-ai', 'Suno AI', 'سونو AI', 'توليد أغاني كاملة بالذكاء الاصطناعي', 'سونو AI يولّد أغاني كاملة بكلمات وألحان وأصوات بشرية من نص بسيط. ثورة في صناعة الموسيقى تتيح لأي شخص إنشاء أغنية احترافية في ثوانٍ.', 'audio', 'freemium', 10, null, ARRAY['أغاني كاملة', 'أصوات بشرية واقعية', 'كلمات + لحن', 'أنواع موسيقى متعددة', '50 أغنية مجانية يومياً'], ARRAY['سهل جداً للمبتدئين', 'جودة موسيقية عالية', 'مجاني بسخاء'], ARRAY['لا يمكن التحكم الكامل بالألحان', 'جودة الكلمات متفاوتة'], 'https://suno.com', 'https://suno.com/logo.svg', 4.5, 5600, ARRAY['music', 'audio', 'song', 'generation', 'creative'], true, '2023-12-20'),

('udio', 'Udio', 'يوديو', 'توليد موسيقى احترافية من النص', 'يوديو منافس قوي لـ Suno في توليد الموسيقى. يتميز بجودة صوتية أعلى وتحكم أكثر في عناصر الأغنية. خيار مفضل للموسيقيين المحترفين.', 'audio', 'freemium', 10, null, ARRAY['جودة صوتية عالية', 'تحكم في الأجزاء', 'تمديد الأغاني', 'remix', '1200 أغنية شهرياً مجاناً'], ARRAY['جودة أعلى من Suno', 'تحكم أكثر', 'مجاني بسخاء'], ARRAY['أبطأ من Suno', 'واجهة أصعب قليلاً'], 'https://udio.com', 'https://udio.com/logo.svg', 4.3, 1200, ARRAY['music', 'audio', 'song', 'professional', 'remix'], false, '2024-04-10'),

('murf-ai', 'Murf AI', 'مرف AI', 'توليد أصوات بشرية احترافية للمحتوى', 'مرف AI منصة متخصصة في تحويل النص إلى كلام بأصوات بشرية طبيعية. تستخدمها شركات المحتوى لإنتاج ملفات صوتية احترافية بـ 100+ صوت بـ 20 لغة.', 'audio', 'freemium', 29, null, ARRAY['100+ صوت بشري', '20 لغة', 'ضبط النبرة والسرعة', 'مزامنة مع الفيديو', 'API متاح'], ARRAY['أصوات طبيعية جداً', 'كثير من اللغات', 'واجهة سهلة'], ARRAY['أغلى من المنافسين', 'محدود في الخطة المجانية'], 'https://murf.ai', 'https://murf.ai/public/assets/logo-w.svg', 4.2, 980, ARRAY['tts', 'voiceover', 'audio', 'content', 'professional'], false, '2020-01-01'),

-- ── WRITING ────────────────────────────────────────────────────────────────
('copy-ai', 'Copy.ai', 'كوبي AI', 'توليد محتوى تسويقي بالذكاء الاصطناعي', 'كوبي AI متخصص في كتابة المحتوى التسويقي: إعلانات وصفحات هبوط ومنشورات وسوم تواصل اجتماعي. يوفر workflow لأتمتة إنتاج المحتوى.', 'writing', 'freemium', 49, null, ARRAY['كتابة الإعلانات', 'صفحات الهبوط', 'منشورات السوشيال ميديا', 'أتمتة المحتوى', '90+ قالب'], ARRAY['متخصص في التسويق', 'قوالب كثيرة', 'مجاني للبدء'], ARRAY['مرتفع السعر للنسخة الكاملة', 'أقل إبداعية من Claude'], 'https://copy.ai', 'https://www.copy.ai/hubfs/copy-ai-logo%201.svg', 4.1, 3400, ARRAY['writing', 'marketing', 'copywriting', 'social-media', 'ads'], false, '2020-10-01'),

('writesonic', 'Writesonic', 'رايتسونيك', 'كتابة مقالات SEO بالذكاء الاصطناعي', 'رايتسونيك متخصص في كتابة مقالات محسّنة لمحركات البحث. يولّد مقالات طويلة مع بحث ويب حديث ومراعاة لنية البحث ومتطلبات Google.', 'writing', 'freemium', 16, null, ARRAY['مقالات SEO', 'بحث ويب', 'Chatsonic مدمج', 'Botsonic للمحادثة', 'صفحات هبوط'], ARRAY['متخصص في SEO', 'سعر منافس', 'بحث ويب مدمج'], ARRAY['جودة العربية متفاوتة', 'يحتاج مراجعة'], 'https://writesonic.com', 'https://writesonic.com/static/images/writesonic-logo.svg', 4.0, 2100, ARRAY['writing', 'seo', 'blog', 'articles', 'marketing'], false, '2020-10-01'),

('sudowrite', 'Sudowrite', 'سودورايت', 'ذكاء اصطناعي للكتّاب الإبداعيين', 'سودورايت مصمم خصيصاً لكتّاب القصص والروايات. يساعد على تطوير الحبكة وبناء الشخصيات وتوسيع المشاهد وتجاوز الحاجز الإبداعي.', 'writing', 'paid', 19, null, ARRAY['كتابة الروايات', 'تطوير الشخصيات', 'توسيع المشاهد', 'أداة Story Bible', 'مقترحات الحبكة'], ARRAY['متخصص في الكتابة الإبداعية', 'ميزات فريدة', 'مجتمع كتّاب نشط'], ARRAY['غير مناسب للكتابة التجارية', 'سعر مرتفع'], 'https://sudowrite.com', 'https://sudowrite.com/logo.png', 4.2, 560, ARRAY['writing', 'fiction', 'novel', 'creative', 'storytelling'], false, '2020-09-01'),

-- ── CODE ────────────────────────────────────────────────────────────────────
('cursor', 'Cursor', 'كيرسر', 'محرر كود بالذكاء الاصطناعي — البديل الذكي لـ VS Code', 'كيرسر محرر كود مبني على VS Code مع ذكاء اصطناعي متكامل. يفهم قاعدة الكود بالكامل ويكتب الكود ويصحح الأخطاء ويجيب على الأسئلة داخل المحرر مباشرة.', 'code', 'freemium', 20, null, ARRAY['فهم قاعدة الكود', 'Composer لكتابة كود جديد', 'Chat مع الكود', 'Tab للإكمال التلقائي', 'دعم كل اللغات'], ARRAY['الأفضل للمطورين', 'يفهم السياق الكامل', 'مجاني بسخاء'], ARRAY['يعتمد على نماذج مدفوعة', 'أبطأ أحياناً على الملفات الكبيرة'], 'https://cursor.com', 'https://cursor.com/assets/images/logo.svg', 4.7, 8900, ARRAY['code', 'ide', 'vscode', 'developer', 'productivity'], true, '2023-03-14'),

('replit', 'Replit', 'ريبليت', 'كتابة وتشغيل الكود في المتصفح بالذكاء الاصطناعي', 'ريبليت منصة تطوير سحابية تتيح كتابة الكود في المتصفح مع مساعد AI يكتب ويصحح ويشرح الكود. مثالي للتعلم والنماذج الأولية السريعة.', 'code', 'freemium', 20, null, ARRAY['IDE في المتصفح', 'Ghostwriter AI', 'نشر تلقائي', '50+ لغة برمجة', 'قوالب جاهزة'], ARRAY['لا يحتاج تثبيت', 'مثالي للتعلم', 'نشر سريع'], ARRAY['أبطأ من المحررات المحلية', 'محدود في الذاكرة'], 'https://replit.com', 'https://replit.com/public/icons/favicon-196.png', 4.1, 4500, ARRAY['code', 'browser', 'learning', 'deploy', 'beginner'], false, '2016-05-01'),

('tabnine', 'Tabnine', 'تابناين', 'إكمال الكود التلقائي بالذكاء الاصطناعي', 'تابناين إضافة لمحررات الكود تكمل الكود تلقائياً بناءً على سياق مشروعك. يعمل داخلياً (on-device) مما يضمن خصوصية الكود. يدعم كل المحررات الرئيسية.', 'code', 'freemium', 12, null, ARRAY['يعمل داخل VS Code وغيرها', 'خصوصية الكود', 'نموذج مدرّب على كودك', 'دعم 30+ لغة', 'يعمل offline'], ARRAY['خصوصية الكود محفوظة', 'يتعلم من كودك', 'يعمل بدون إنترنت'], ARRAY['أقل ذكاءً من Copilot', 'الإصدار المجاني محدود'], 'https://tabnine.com', 'https://www.tabnine.com/wp-content/uploads/2023/11/tabnine-logo.svg', 3.9, 1200, ARRAY['code', 'autocomplete', 'privacy', 'offline', 'vscode'], false, '2019-06-01'),

('bolt-new', 'Bolt.new', 'بولت', 'بناء تطبيقات ويب كاملة بمحادثة', 'بولت من StackBlitz يبني تطبيقات ويب كاملة في المتصفح بمجرد وصف ما تريد. ينشئ الكود ويثبت المكتبات ويعرض النتيجة فوراً. ثورة في بناء النماذج الأولية.', 'code', 'freemium', 20, null, ARRAY['بناء تطبيقات من النص', 'تشغيل فوري في المتصفح', 'دعم React وNext.js', 'نشر على Netlify', 'تعديل بالمحادثة'], ARRAY['سريع جداً للنماذج الأولية', 'لا يحتاج تثبيت', 'مذهل للمبتدئين'], ARRAY['غير مناسب للمشاريع الكبيرة', 'حدود شهرية'], 'https://bolt.new', 'https://bolt.new/favicon.svg', 4.5, 3200, ARRAY['code', 'web', 'prototype', 'no-code', 'react'], false, '2024-10-01'),

-- ── PRODUCTIVITY ────────────────────────────────────────────────────────────
('otter-ai', 'Otter.ai', 'أوتر AI', 'تفريغ الاجتماعات والمحادثات تلقائياً', 'أوتر AI يسجّل ويفرّغ الاجتماعات تلقائياً ويلخّصها ويستخرج النقاط الرئيسية. يتكامل مع Zoom وGoogle Meet وMicrosoft Teams.', 'productivity', 'freemium', 17, null, ARRAY['تفريغ تلقائي', 'تلخيص الاجتماعات', 'تكامل مع Zoom وMeet', 'بحث في النصوص', 'مشاركة الملاحظات'], ARRAY['دقيق في التفريغ', 'سهل الاستخدام', 'يوفر وقتاً كبيراً'], ARRAY['دقة أقل مع الأصوات غير الإنجليزية', 'محدود في الخطة المجانية'], 'https://otter.ai', 'https://otter.ai/static/images/otter-logo.svg', 4.2, 2300, ARRAY['meeting', 'transcription', 'productivity', 'zoom', 'notes'], false, '2016-02-01'),

('mem-ai', 'Mem.ai', 'ميم AI', 'الذاكرة الثانية الذكية لتنظيم الأفكار', 'ميم AI تطبيق ذاكرة ذكية يحفظ ويرتّب ويسترجع الملاحظات تلقائياً. يجد الروابط بين الأفكار ويجيب على أسئلتك انطلاقاً من ملاحظاتك الشخصية.', 'productivity', 'freemium', 14, null, ARRAY['ذاكرة ذكية', 'ربط الأفكار تلقائياً', 'بحث ذكي', 'تنظيم تلقائي', 'واجهة بسيطة'], ARRAY['لا يحتاج تنظيم يدوي', 'يجد الروابط تلقائياً'], ARRAY['أغلى من المنافسين', 'يفتقر لبعض الميزات المتقدمة'], 'https://mem.ai', 'https://mem.ai/images/mem-logo.svg', 3.9, 430, ARRAY['notes', 'memory', 'knowledge', 'productivity', 'pkm'], false, '2020-01-01'),

('taskade', 'Taskade', 'تاسكيد', 'إدارة المشاريع والمهام بالذكاء الاصطناعي', 'تاسكيد يجمع إدارة المهام والمشاريع والمحادثة الجماعية في أداة واحدة مع مساعد AI. يولّد المهام ويعدّ الخطط ويوزّع العمل تلقائياً.', 'productivity', 'freemium', 19, null, ARRAY['مهام ومشاريع AI', 'محادثة جماعية', 'خرائط ذهنية', 'قوالب AI', 'تعاون الفريق'], ARRAY['شامل في ميزاته', 'مناسب للفرق', 'قوالب AI مفيدة'], ARRAY['كثير من الميزات = تعقيد', 'أداء التطبيق أحياناً بطيء'], 'https://taskade.com', 'https://www.taskade.com/static/images/logos/taskade-logo.svg', 4.0, 670, ARRAY['productivity', 'tasks', 'projects', 'team', 'ai-assistant'], false, '2017-09-01'),

-- ── SEO ─────────────────────────────────────────────────────────────────────
('semrush-ai', 'Semrush AI', 'سيمراش AI', 'أقوى أداة SEO مع ميزات الذكاء الاصطناعي', 'سيمراش منصة SEO شاملة تضم ميزات AI لتحليل الكلمات المفتاحية والمنافسين وبناء الروابط وتحسين المحتوى. المعيار الذهبي في مجال SEO.', 'seo', 'paid', 139, null, ARRAY['تحليل الكلمات المفتاحية', 'تحليل المنافسين', 'بناء الروابط', 'ContentShake AI', 'تحليل الموقع'], ARRAY['الأشمل في SEO', 'بيانات دقيقة', 'أدوات AI مدمجة'], ARRAY['سعر مرتفع جداً', 'معقد للمبتدئين'], 'https://semrush.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Semrush-logo-2022.svg/120px-Semrush-logo-2022.svg.png', 4.5, 6700, ARRAY['seo', 'keywords', 'competitor', 'backlinks', 'professional'], false, '2008-01-01'),

('surfer-seo', 'Surfer SEO', 'سيرفر SEO', 'تحسين محتوى المقالات للتصدر في Google', 'سيرفر SEO يحلّل المقالات المتصدرة ويعطيك توجيهات دقيقة لتحسين محتواك. يقترح الكلمات المفتاحية والعناوين والطول المثالي للمقال.', 'seo', 'paid', 99, null, ARRAY['تحليل SERP', 'Content Editor', 'Audit للموقع', 'Grow Flow', 'Keyword Research'], ARRAY['توجيهات دقيقة للمحتوى', 'سهل الفهم', 'نتائج واضحة'], ARRAY['سعر مرتفع', 'يركز على المحتوى فقط'], 'https://surferseo.com', 'https://surferseo.com/wp-content/themes/surferseo-theme-v2/src/img/surfer-logo.svg', 4.3, 2100, ARRAY['seo', 'content', 'optimization', 'google', 'writing'], false, '2017-01-01'),

('ahrefs', 'Ahrefs', 'أهريفز', 'تحليل الروابط الخلفية والكلمات المفتاحية', 'أهريفز منصة SEO قوية تتميز بأكبر قاعدة بيانات روابط خلفية. تساعد على تحليل المنافسين واكتشاف فرص الكلمات المفتاحية وتتبع الترتيب.', 'seo', 'paid', 129, null, ARRAY['قاعدة بيانات الروابط الأكبر', 'Site Explorer', 'Keywords Explorer', 'Content Explorer', 'AI Content Helper'], ARRAY['بيانات الروابط الأدق', 'واجهة احترافية', 'تحديثات متكررة'], ARRAY['سعر مرتفع', 'معقد للمبتدئين'], 'https://ahrefs.com', 'https://static.ahrefs.com/static/assets/img/ahrefs-logo-print.svg', 4.6, 4300, ARRAY['seo', 'backlinks', 'keywords', 'competitor', 'professional'], false, '2010-07-01'),

-- ── DESIGN ──────────────────────────────────────────────────────────────────
('figma-ai', 'Figma AI', 'فيغما AI', 'تصميم واجهات المستخدم بمساعدة الذكاء الاصطناعي', 'فيغما AI ميزات الذكاء الاصطناعي المدمجة في فيغما تشمل Make Designs لتوليد التصاميم من النص وSearch الذكي واقتراحات التصميم التلقائية.', 'design', 'freemium', 15, null, ARRAY['Make Designs', 'بحث ذكي', 'اقتراحات تلقائية', 'تصدير المكونات', 'تعاون الفريق'], ARRAY['مدمج في Figma', 'معيار الصناعة', 'مجاني للبدء'], ARRAY['AI لا يزال تجريبياً', 'يحتاج تعلم Figma أولاً'], 'https://figma.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/100px-Figma-logo.svg.png', 4.4, 7800, ARRAY['design', 'ui', 'ux', 'figma', 'prototype'], true, '2024-06-26'),

('looka', 'Looka', 'لووكا', 'تصميم شعارات احترافية بالذكاء الاصطناعي', 'لووكا يصمم شعارات احترافية بناءً على اسم شركتك ومجالها وتفضيلاتك. يولّد عشرات الخيارات في ثوانٍ ويوفر حزمة هوية بصرية كاملة.', 'design', 'paid', 20, null, ARRAY['شعارات AI', 'هوية بصرية كاملة', 'بطاقات عمل', 'ملفات للطباعة', 'تخصيص كامل'], ARRAY['سهل جداً', 'نتائج احترافية', 'حزمة هوية بصرية'], ARRAY['مدفوع للتحميل', 'لا يناسب العلامات الكبرى'], 'https://looka.com', 'https://looka.com/og/looka-logo.png', 4.1, 3200, ARRAY['logo', 'branding', 'design', 'business', 'identity'], false, '2016-01-01'),

('khroma', 'Khroma', 'خروما', 'توليد لوحات ألوان بالذكاء الاصطناعي', 'خروما يتعلم تفضيلاتك اللونية ثم يولّد لوحات ألوان لا نهاية لها مناسبة لمشاريعك التصميمية. مجاني تماماً ومثالي للمصممين.', 'design', 'free', null, null, ARRAY['لوحات ألوان لا محدودة', 'يتعلم من تفضيلاتك', 'معاينة على نصوص وأزرار', 'حفظ اللوحات المفضلة', 'مجاني'], ARRAY['مجاني تماماً', 'لوحات مخصصة', 'سهل الاستخدام'], ARRAY['لا يصدر ملفات تصميم', 'ميزات محدودة'], 'https://khroma.co', 'https://khroma.co/img/logo.svg', 4.0, 280, ARRAY['design', 'colors', 'palette', 'free', 'ui'], false, '2018-01-01'),

-- ── DATA ─────────────────────────────────────────────────────────────────────
('julius-ai', 'Julius AI', 'جوليوس AI', 'تحليل البيانات ورسم الرسوم البيانية بالمحادثة', 'جوليوس AI يحلّل ملفات Excel وCSV ويرسم رسوماً بيانية ويجيب على أسئلتك عن البيانات بالمحادثة. لا يحتاج مهارات برمجية.', 'data', 'freemium', 22, null, ARRAY['رفع ملفات Excel وCSV', 'رسوم بيانية تلقائية', 'تحليل إحصائي', 'Python مدمج', 'تقارير PDF'], ARRAY['سهل بدون برمجة', 'رسوم بيانية احترافية', 'يجيب بالعربية'], ARRAY['حدود في الخطة المجانية', 'أحياناً بطيء على الملفات الكبيرة'], 'https://julius.ai', 'https://julius.ai/logo.png', 4.3, 890, ARRAY['data', 'excel', 'charts', 'analysis', 'no-code'], false, '2023-06-01'),

('obviously-ai', 'Obviously AI', 'أوبفيوسلي AI', 'بناء نماذج تنبؤية بدون كود', 'أوبفيوسلي AI يبني نماذج تنبؤية من بياناتك في دقائق بدون كتابة سطر كود واحد. يتنبأ بالمبيعات ومعدلات التوقف وغيرها.', 'data', 'paid', 75, null, ARRAY['نماذج تنبؤية', 'بدون كود', 'تحليل CSV', 'API للنتائج', 'تقارير آلية'], ARRAY['لا يحتاج مهارات AI', 'سريع جداً', 'نتائج قابلة للتفسير'], ARRAY['سعر مرتفع', 'محدود للبيانات الكبيرة جداً'], 'https://obviously.ai', 'https://obviously.ai/logo.png', 3.8, 340, ARRAY['data', 'prediction', 'ml', 'no-code', 'business'], false, '2019-01-01'),

('tableau-ai', 'Tableau AI', 'تابلو AI', 'تصور البيانات بالذكاء الاصطناعي', 'تابلو مع Einstein AI يقدم تصورات بصرية تفاعلية للبيانات مع ميزات AI تشمل التفسير التلقائي والاقتراحات الذكية. المعيار في مجال تحليل البيانات المرئية.', 'data', 'paid', 75, null, ARRAY['تصور تفاعلي', 'Einstein AI', 'اتصال بقواعد البيانات', 'لوحات متحركة', 'تنبؤات AI'], ARRAY['قوة بصرية استثنائية', 'موثوق في المؤسسات', 'تكامل واسع'], ARRAY['سعر مرتفع جداً', 'منحنى تعلم حاد'], 'https://tableau.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Tableau_Logo.png/120px-Tableau_Logo.png', 4.3, 5600, ARRAY['data', 'visualization', 'bi', 'enterprise', 'charts'], false, '2003-01-01')

ON CONFLICT (slug) DO NOTHING;
