/**
 * Mock data — used when Supabase is not configured (dev/demo mode)
 */
import { Tool } from './types'

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1',
    slug: 'chatgpt',
    name: 'ChatGPT',
    name_ar: 'شات جي بي تي',
    tagline_ar: 'أشهر نموذج محادثة بالذكاء الاصطناعي من OpenAI',
    description_ar:
      'ChatGPT هو نموذج لغوي ضخم من OpenAI قادر على المحادثة، كتابة المحتوى، البرمجة، الترجمة وأكثر. يدعم اللغة العربية بشكل جيد ويتوفر بنسخة مجانية ومدفوعة.',
    category: 'chatbot',
    pricing: 'freemium',
    price_monthly: 20,
    price_yearly: 200,
    features: ['محادثة طبيعية', 'كتابة محتوى', 'برمجة', 'تحليل ملفات', 'توليد صور (Plus)'],
    pros: ['واجهة سهلة', 'يدعم العربية', 'نسخة مجانية كافية', 'GPT-4 قوي جداً'],
    cons: ['النسخة المجانية بطيئة أحياناً', 'قد يُنتج معلومات خاطئة'],
    website_url: 'https://chat.openai.com',
    logo_url: '/logos/chatgpt.svg',
    screenshot_url: null,
    rating: 4.8,
    reviews_count: 1240,
    tags: ['chatgpt', 'openai', 'gpt4', 'محادثة', 'كتابة'],
    is_featured: true,
    launched_at: '2022-11-30',
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'gemini',
    name: 'Gemini',
    name_ar: 'جيميني',
    tagline_ar: 'نموذج Google متعدد الوسائط لفهم النصوص والصور',
    description_ar:
      'Gemini هو نموذج الذكاء الاصطناعي من Google، يتميز بالتكامل مع خدمات Google وقدرته على فهم النصوص والصور والصوت في نفس الوقت.',
    category: 'chatbot',
    pricing: 'freemium',
    price_monthly: 19.99,
    price_yearly: 199,
    features: ['محادثة متعددة الوسائط', 'تكامل Google Workspace', 'Gemini Advanced (Gemini 1.5 Pro)', 'بحث في الويب'],
    pros: ['مجاني بشكل كبير', 'متكامل مع Google', 'سريع جداً', 'فهم الصور ممتاز'],
    cons: ['أقل دقة من GPT-4 في بعض المهام', 'دعم العربية متفاوت'],
    website_url: 'https://gemini.google.com',
    logo_url: '/logos/gemini.svg',
    screenshot_url: null,
    rating: 4.5,
    reviews_count: 890,
    tags: ['gemini', 'google', 'ai', 'محادثة'],
    is_featured: true,
    launched_at: '2023-12-06',
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'midjourney',
    name: 'Midjourney',
    name_ar: 'ميدجورني',
    tagline_ar: 'أفضل أداة لتوليد الصور الاحترافية بالذكاء الاصطناعي',
    description_ar:
      'Midjourney هي أداة توليد صور بالذكاء الاصطناعي تُنتج صوراً فنية احترافية بجودة عالية جداً. تعمل عبر Discord وتتميز بأسلوبها الفني المميز.',
    category: 'image',
    pricing: 'paid',
    price_monthly: 10,
    price_yearly: 96,
    features: ['توليد صور احترافية', 'تنويع الأساليب الفنية', 'دقة عالية جداً', 'تعديل الصور'],
    pros: ['جودة لا مثيل لها', 'أساليب فنية متنوعة', 'مجتمع ضخم'],
    cons: ['لا نسخة مجانية', 'يعمل عبر Discord فقط', 'لا يدعم العربية في البرومبت بشكل كامل'],
    website_url: 'https://midjourney.com',
    logo_url: '/logos/midjourney.svg',
    screenshot_url: null,
    rating: 4.7,
    reviews_count: 2100,
    tags: ['midjourney', 'صور', 'فن', 'تصميم'],
    is_featured: true,
    launched_at: '2022-03-14',
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'claude',
    name: 'Claude',
    name_ar: 'كلود',
    tagline_ar: 'نموذج Anthropic الآمن والدقيق لتحليل المستندات والكتابة',
    description_ar:
      'Claude من Anthropic يتميز بسياق طويل جداً (200K توكن)، وهو ممتاز لتحليل المستندات الطويلة والكتابة الإبداعية والبرمجة. يُعدّ من أكثر النماذج أماناً.',
    category: 'chatbot',
    pricing: 'freemium',
    price_monthly: 20,
    price_yearly: 200,
    features: ['سياق 200K توكن', 'تحليل ملفات PDF', 'كتابة إبداعية', 'برمجة دقيقة', 'بحث في الويب'],
    pros: ['سياق طويل جداً', 'أمان عالٍ', 'تحليل مستندات ممتاز', 'استجابات دقيقة'],
    cons: ['بطيء أحياناً مقارنة بـ GPT-4', 'قيود في بعض المواضيع'],
    website_url: 'https://claude.ai',
    logo_url: '/logos/claude.svg',
    screenshot_url: null,
    rating: 4.6,
    reviews_count: 670,
    tags: ['claude', 'anthropic', 'محادثة', 'تحليل'],
    is_featured: true,
    launched_at: '2023-03-14',
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'dall-e-3',
    name: 'DALL·E 3',
    name_ar: 'دالي 3',
    tagline_ar: 'توليد صور من النص مع دعم ممتاز للغة العربية',
    description_ar:
      'DALL·E 3 من OpenAI يتميز بفهمه العميق للتعليمات النصية وقدرته على إنتاج صور دقيقة تعكس الوصف بتفاصيله. متاح داخل ChatGPT Plus.',
    category: 'image',
    pricing: 'freemium',
    price_monthly: 20,
    price_yearly: 200,
    features: ['توليد صور من نص', 'فهم عميق للتعليمات', 'متكامل مع ChatGPT', 'دعم جيد للعربية'],
    pros: ['فهم التعليمات بدقة عالية', 'متاح مع ChatGPT Plus', 'جودة ممتازة'],
    cons: ['يحتاج اشتراك Plus', 'أبطأ من بعض المنافسين'],
    website_url: 'https://openai.com/dall-e-3',
    logo_url: '/logos/dalle.svg',
    screenshot_url: null,
    rating: 4.5,
    reviews_count: 540,
    tags: ['dalle', 'openai', 'صور', 'توليد'],
    is_featured: false,
    launched_at: '2023-10-01',
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'perplexity',
    name: 'Perplexity AI',
    name_ar: 'بيربلكسيتي',
    tagline_ar: 'محرك بحث ذكي يجيب بمصادر موثوقة ومحدّثة',
    description_ar:
      'Perplexity هو محرك بحث مدعوم بالذكاء الاصطناعي يبحث في الإنترنت ويجيب بإجابات شاملة مع ذكر المصادر. مثالي للبحث الأكاديمي والأخبار.',
    category: 'productivity',
    pricing: 'freemium',
    price_monthly: 20,
    price_yearly: 200,
    features: ['بحث في الويب بالوقت الفعلي', 'ذكر المصادر', 'ملخصات دقيقة', 'نسخة Pro مع GPT-4'],
    pros: ['مجاني وسريع', 'مصادر موثوقة', 'معلومات حديثة'],
    cons: ['أقل إبداعاً من ChatGPT', 'يحتاج إنترنت دائماً'],
    website_url: 'https://perplexity.ai',
    logo_url: '/logos/perplexity.svg',
    screenshot_url: null,
    rating: 4.4,
    reviews_count: 430,
    tags: ['perplexity', 'بحث', 'مصادر', 'أخبار'],
    is_featured: false,
    launched_at: '2022-08-01',
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    name_ar: 'جيت هاب كوبايلوت',
    tagline_ar: 'مساعد البرمجة الذكي المدمج مع VS Code وجميع المحررات',
    description_ar:
      'GitHub Copilot يقترح كوداً كاملاً أثناء الكتابة، يفهم السياق ويكتب دوال ووحدات اختبار. مدمج مع VS Code و JetBrains وغيرها.',
    category: 'code',
    pricing: 'paid',
    price_monthly: 10,
    price_yearly: 100,
    features: ['إكمال الكود تلقائياً', 'كتابة اختبارات', 'شرح الكود', 'دعم 20+ لغة برمجة', 'Chat داخل المحرر'],
    pros: ['توفير وقت هائل', 'مدمج مع GitHub', 'دعم ممتاز لـ Python وJS'],
    cons: ['مدفوع بالكامل', 'قد يقترح كوداً غير آمن أحياناً'],
    website_url: 'https://github.com/features/copilot',
    logo_url: '/logos/copilot.svg',
    screenshot_url: null,
    rating: 4.7,
    reviews_count: 1800,
    tags: ['copilot', 'github', 'كود', 'برمجة', 'vscode'],
    is_featured: true,
    launched_at: '2021-06-29',
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    name_ar: 'ستيبل ديفيوجن',
    tagline_ar: 'نموذج توليد صور مفتوح المصدر يعمل على جهازك مجاناً',
    description_ar:
      'Stable Diffusion نموذج مفتوح المصدر لتوليد الصور يمكن تشغيله على جهازك بدون اشتراك. يتيح تخصيصاً كاملاً عبر الـ fine-tuning والـ LoRA.',
    category: 'image',
    pricing: 'free',
    price_monthly: null,
    price_yearly: null,
    features: ['مفتوح المصدر', 'يعمل محلياً', 'LoRA وfine-tuning', 'آلاف الموديلات', 'بدون قيود محتوى'],
    pros: ['مجاني تماماً', 'تحكم كامل', 'مجتمع ضخم ونشط'],
    cons: ['يحتاج GPU قوي', 'الإعداد معقد للمبتدئين'],
    website_url: 'https://stability.ai',
    logo_url: '/logos/sd.svg',
    screenshot_url: null,
    rating: 4.5,
    reviews_count: 3200,
    tags: ['stable diffusion', 'صور', 'مفتوح المصدر', 'AI art'],
    is_featured: false,
    launched_at: '2022-08-22',
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    slug: 'notion-ai',
    name: 'Notion AI',
    name_ar: 'نوشن AI',
    tagline_ar: 'الذكاء الاصطناعي مدمج داخل Notion لتحسين الكتابة والملاحظات',
    description_ar:
      'Notion AI يضيف قدرات الذكاء الاصطناعي مباشرة داخل Notion. يساعد في كتابة المستندات، التلخيص، الترجمة وتوليد أفكار جديدة.',
    category: 'writing',
    pricing: 'freemium',
    price_monthly: 10,
    price_yearly: 96,
    features: ['كتابة وتحسين النصوص', 'تلخيص المستندات', 'ترجمة', 'توليد قوائم وجداول', 'مدمج مع Notion'],
    pros: ['مدمج مع workspace', 'سهولة الاستخدام', 'ممتاز للفرق'],
    cons: ['يحتاج اشتراك Notion', 'محدود خارج Notion'],
    website_url: 'https://notion.so/product/ai',
    logo_url: '/logos/notion.svg',
    screenshot_url: null,
    rating: 4.3,
    reviews_count: 560,
    tags: ['notion', 'كتابة', 'إنتاجية', 'ملاحظات'],
    is_featured: false,
    launched_at: '2023-02-22',
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    slug: 'runway-ml',
    name: 'Runway',
    name_ar: 'رانوي',
    tagline_ar: 'منصة توليد الفيديو بالذكاء الاصطناعي للمحترفين',
    description_ar:
      'Runway هي المنصة الرائدة في توليد وتحرير الفيديو بالذكاء الاصطناعي. تتيح تحويل النص لفيديو، إزالة الخلفية، التحريك وأكثر.',
    category: 'video',
    pricing: 'freemium',
    price_monthly: 15,
    price_yearly: 144,
    features: ['توليد فيديو من نص', 'إزالة الخلفية تلقائياً', 'تحريك الصور', 'Gen-2 model', 'تحرير AI'],
    pros: ['جودة فيديو عالية', 'واجهة احترافية', 'أدوات تحرير متقدمة'],
    cons: ['الخطة المجانية محدودة جداً', 'سعر مرتفع للإنتاج الكثيف'],
    website_url: 'https://runwayml.com',
    logo_url: '/logos/runway.svg',
    screenshot_url: null,
    rating: 4.4,
    reviews_count: 720,
    tags: ['runway', 'فيديو', 'توليد', 'تحرير'],
    is_featured: true,
    launched_at: '2023-06-01',
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    name_ar: 'إليفن لابز',
    tagline_ar: 'أفضل أداة لتوليد الصوت البشري الطبيعي بالذكاء الاصطناعي',
    description_ar:
      'ElevenLabs تنتج أصواتاً بشرية واقعية بالذكاء الاصطناعي. يمكن استنساخ أي صوت، بناء شخصيات صوتية وتوليد تعليق صوتي بأكثر من 30 لغة.',
    category: 'audio',
    pricing: 'freemium',
    price_monthly: 5,
    price_yearly: 55,
    features: ['توليد صوت بشري', 'استنساخ الأصوات', '30+ لغة', 'API متاح', 'صوت عربي ممتاز'],
    pros: ['جودة صوت لا مثيل لها', 'دعم العربية ممتاز', 'API سهل الاستخدام'],
    cons: ['الخطة المجانية 10 دقائق فقط', 'استنساخ الأصوات يحتاج خطة مدفوعة'],
    website_url: 'https://elevenlabs.io',
    logo_url: '/logos/elevenlabs.svg',
    screenshot_url: null,
    rating: 4.8,
    reviews_count: 940,
    tags: ['elevenlabs', 'صوت', 'TTS', 'عربي', 'بودكاست'],
    is_featured: true,
    launched_at: '2022-01-01',
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    slug: 'jasper-ai',
    name: 'Jasper AI',
    name_ar: 'جاسبر AI',
    tagline_ar: 'أداة كتابة محتوى تسويقي احترافي بالذكاء الاصطناعي',
    description_ar:
      'Jasper متخصص في كتابة المحتوى التسويقي: إعلانات، مقالات SEO، منشورات سوشيال ميديا وأكثر. يحتوي على 50+ قالب جاهز.',
    category: 'writing',
    pricing: 'paid',
    price_monthly: 39,
    price_yearly: 468,
    features: ['50+ قالب محتوى', 'كتابة SEO', 'محتوى سوشيال ميديا', 'Brand voice', 'فريق تعاوني'],
    pros: ['متخصص في التسويق', 'قوالب احترافية', 'دعم الفرق'],
    cons: ['سعر مرتفع', 'لا نسخة مجانية', 'أقل إبداعاً من ChatGPT'],
    website_url: 'https://jasper.ai',
    logo_url: '/logos/jasper.svg',
    screenshot_url: null,
    rating: 4.2,
    reviews_count: 380,
    tags: ['jasper', 'كتابة', 'تسويق', 'SEO', 'محتوى'],
    is_featured: false,
    launched_at: '2021-01-01',
    updated_at: new Date().toISOString(),
  },
]
